
import sys
import os
import time
from dotenv import load_dotenv
import agentic_system
import argparse
from run_simulation import run_simulation

# Load the .env file from the parent directory
current_dir = os.path.dirname(__file__)
dotenv_path = os.path.join(current_dir, "..", ".env")
load_dotenv(dotenv_path=dotenv_path)

# Configure the Gemini API key
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    print("Error: GEMINI_API_KEY not found in .env file")
    sys.exit(1)

agentic_system.genai.configure(api_key=api_key)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the agentic system.")
    parser.add_argument("command", nargs="?", default="Form a line and patrol the area.",
                        help="The natural language command for the drone swarm.")
    parser.add_argument("--hive-mind", action="store_true", help="Enable hive mind mode.")
    parser.add_argument("--test-hive-mind", action="store_true", help="Run a test of the hive mind controller.")
    args = parser.parse_args()

    simulation_process = None
    if args.test_hive_mind:
        try:
            simulation_process = run_simulation()
            # Give the simulation time to start up
            time.sleep(10)

            # This is a test to see the output of the HiveMindController
            # In a real scenario, the plan would be generated by the agentic_system
            test_plan = {
                "task": "patrol",
                "area": "0,0,2",
                "swarm": {
                    "formation": "grid",
                    "behavior": "patrol"
                },
                "priority": "high"
            }
            from hive_mind import HiveMindController
            controller = HiveMindController(test_plan)
            controller.execute()
            # Keep the script running to observe the simulation
            print("Press Ctrl+C to exit.")
            while True:
                time.sleep(1)
        finally:
            if simulation_process:
                print("Terminating simulation...")
                simulation_process.terminate()
    else:
        plan = agentic_system.agentic_system(args.command, hive_mind_enabled=args.hive_mind)
        print("Structured Plan:", plan)
